apiVersion: apps/v1
kind: Deployment
metadata:
  name: life-support
  labels:
    app: life-support
spec:
  replicas: 1
  selector:
    matchLabels:
      app: life-support
  template:
    metadata:
      labels:
        app: life-support
    spec:
      containers:
        - name: life-support
          image: polinux/stress
          command: ["stress"]
          args: ["--vm", "1", "--vm-bytes", "200M", "--vm-hang", "1"]
          resources:
            limits:
              memory: "64Mi"   # limit lower than usage → OOMKilled
              cpu: "100m"
